import { IProduct } from './iproduct.interface';

export const PRODUCTS: IProduct[] = [
  {
    id: 1,
    name: 'Headphones',
    price: 59,
    description:
      'Noise-cancelling over-ear headphones with 40 hours of battery life and deep bass sound.',
    imageUrl: 'headphones-bluetooth.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 2,
    name: 'Smartwatch',
    price: 199,
    description:
      'Fitness and health tracking smartwatch with heart rate monitor and customizable watch faces.',
    imageUrl: 'smartwatch.jpg',
    availability: false,
    quantity: 1,
  },
  {
    id: 3,
    name: 'Smart TV',
    price: 429,
    description: 'Crystal-clear 4K display with HDR, built-in streaming apps, and voice control.',
    imageUrl: 'smart-tv.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 4,
    name: 'Gaming Laptop"',
    price: 1199,
    description: 'High-performance laptop with Intel i7 processor, RTX 4060 GPU, and 16GB RAM.',
    imageUrl: 'laptop-gaming.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 5,
    name: 'Air Purifier',
    price: 149,
    description:
      'Removes 99.97% of dust, allergens, and odors with a 3-stage HEPA filtration system.',
    imageUrl: 'air-purifier.jpg',
    availability: false,
    quantity: 0,
  },
  {
    id: 6,
    name: 'Water Bottle',
    price: 19,
    description: 'Insulated water bottle keeps drinks hot for 12 hours or cold for 24 hours.',
    imageUrl: 'bottle.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 7,
    name: 'Charging Pad',
    price: 25,
    description: 'Fast wireless charging pad compatible with all Qi-enabled smartphones.',
    imageUrl: 'charging-pad.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 8,
    name: 'Pillow',
    price: 35,
    description: 'Ergonomic pillow for neck support and optimal comfort during sleep.',
    imageUrl: 'pillow.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 9,
    name: 'Wallet',
    price: 29,
    description: 'Slim and stylish genuine faux leather wallet with RFID blocking technology.',
    imageUrl: 'wallet.jpg',
    availability: true,
    quantity: 1,
  },
];
