import { IProduct } from './iproduct.interface';

export const PRODUCTS: IProduct[] = [
  {
    id: 1,
    name: 'Pizza Margherita',
    price: 9,
    description: 'Classic Italian pizza with fresh mozzarella, tomatoes, and basil.',
    imageUrl: 'pizza-margherita.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 2,
    name: 'Veggie Pepperoni Pizza',
    price: 10,
    description: 'A delicious pizza topped with spicy pepperoni and mozzarella cheese.',
    imageUrl: 'pizza-pepperoni.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 3,
    name: 'Veggie Chicken Pizza',
    price: 11,
    description: 'Grilled veggie chicken, BBQ sauce, sweetcorn, and mozzarella cheese.',
    imageUrl: 'pizza-veggie-chicken.jpg',
    availability: false,
    quantity: 0,
  },
  {
    id: 4,
    name: 'Hawaiian Pizza',
    price: 11,
    description: 'A sweet and savory blend of vegan ham, pineapple, and melted cheese.',
    imageUrl: 'pizza-hawaiian.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 5,
    name: 'Veggie Delight Pizza',
    price: 10,
    description:
      'Loaded with bell peppers, onions, black and green olives, mushrooms, and tomatoes.',
    imageUrl: 'pizza-veggie-delight.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 6,
    name: 'Four Cheese Pizza',
    price: 11,
    description: 'A rich mix of mozzarella, gorgonzola, parmesan, and provolone cheeses.',
    imageUrl: 'pizza-four-cheese.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 7,
    name: 'Vegan Meat Lovers Pizza',
    price: 12,
    description: 'Topped with vegan pepperoni, sausage, bacon, ham and a lot of veggies.',
    imageUrl: 'pizza-meat-lovers.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 8,
    name: 'Truffle Mushroom Pizza',
    price: 15,
    description: 'Gourmet pizza with truffle oil, wild mushrooms, and creamy mozzarella.',
    imageUrl: 'pizza-truffle-mushroom.jpg',
    availability: true,
    quantity: 1,
  },
  {
    id: 9,
    name: 'Vegan Chicken Pizza',
    price: 12,
    description: 'Spicy buffalo sauce with vegan grilled chicken, onions, and vegan blue cheese.',
    imageUrl: 'pizza-buffalo-vegan-chicken.jpg',
    availability: true,
    quantity: 1,
  },
];
